// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/dashboard/page.tsx
{
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  handler satisfies AppPageConfig<"/dashboard">
}

// Validate ../../src/app/(app)/onboarding/business/page.tsx
{
  const handler = {} as typeof import("../../src/app/(app)/onboarding/business/page.js")
  handler satisfies AppPageConfig<"/onboarding/business">
}

// Validate ../../src/app/(mkt)/pricing/page.tsx
{
  const handler = {} as typeof import("../../src/app/(mkt)/pricing/page.js")
  handler satisfies AppPageConfig<"/pricing">
}

// Validate ../../src/app/page.tsx
{
  const handler = {} as typeof import("../../src/app/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../src/app/api/analytics/links/timeseries/route.ts
{
  const handler = {} as typeof import("../../src/app/api/analytics/links/timeseries/route.js")
  handler satisfies RouteHandlerConfig<"/api/analytics/links/timeseries">
}

// Validate ../../src/app/api/auth/email/route.ts
{
  const handler = {} as typeof import("../../src/app/api/auth/email/route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/email">
}

// Validate ../../src/app/api/businesses/me/route.ts
{
  const handler = {} as typeof import("../../src/app/api/businesses/me/route.js")
  handler satisfies RouteHandlerConfig<"/api/businesses/me">
}

// Validate ../../src/app/api/businesses/upsert/route.ts
{
  const handler = {} as typeof import("../../src/app/api/businesses/upsert/route.js")
  handler satisfies RouteHandlerConfig<"/api/businesses/upsert">
}

// Validate ../../src/app/api/digest/daily/route.ts
{
  const handler = {} as typeof import("../../src/app/api/digest/daily/route.js")
  handler satisfies RouteHandlerConfig<"/api/digest/daily">
}

// Validate ../../src/app/api/health/route.ts
{
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  handler satisfies RouteHandlerConfig<"/api/health">
}

// Validate ../../src/app/api/places/autocomplete/route.ts
{
  const handler = {} as typeof import("../../src/app/api/places/autocomplete/route.js")
  handler satisfies RouteHandlerConfig<"/api/places/autocomplete">
}

// Validate ../../src/app/api/places/details/route.ts
{
  const handler = {} as typeof import("../../src/app/api/places/details/route.js")
  handler satisfies RouteHandlerConfig<"/api/places/details">
}

// Validate ../../src/app/api/qr/route.ts
{
  const handler = {} as typeof import("../../src/app/api/qr/route.js")
  handler satisfies RouteHandlerConfig<"/api/qr">
}

// Validate ../../src/app/api/reviews/send/route.ts
{
  const handler = {} as typeof import("../../src/app/api/reviews/send/route.js")
  handler satisfies RouteHandlerConfig<"/api/reviews/send">
}

// Validate ../../src/app/api/stripe/checkout/route.ts
{
  const handler = {} as typeof import("../../src/app/api/stripe/checkout/route.js")
  handler satisfies RouteHandlerConfig<"/api/stripe/checkout">
}

// Validate ../../src/app/api/webhooks/stripe/route.ts
{
  const handler = {} as typeof import("../../src/app/api/webhooks/stripe/route.js")
  handler satisfies RouteHandlerConfig<"/api/webhooks/stripe">
}





// Validate ../../src/app/layout.tsx
{
  const handler = {} as typeof import("../../src/app/layout.js")
  handler satisfies LayoutConfig<"/">
}
